### ISSUE TITLE
CSS: 用CSS实现一个三角形

### ISSUE THREAD

**Issue by leslie1943** [leslie1943/blog#164]
## 三角形基本思路
1. `width` 和 `height` 都为 `0px`
2. 分别设置容器的border,其中任意三个border的可见度为0即可

````css
.box {
  width: 0px;
  height: 0px;
  border-top: 20px solid rgba(48, 31, 141, 0);
  border-right: 20px solid rgba(29, 114, 117, 1);
  border-bottom: 20px solid rgba(170, 22, 136, 0);
  border-left: 20px solid rgba(144, 175, 29, 1);
}
```
