### ISSUE TITLE
CSS: 实现水平垂直居中的几种方案

### ISSUE THREAD

**Issue by leslie1943** [leslie1943/blog#36]
#### 一: 水平居中(margin: 0 auto)
```css
.horizontal-center {
	background-color: #809399;
	height: 100px;
	width: 200px;
	line-height: 100px;
	text-align: center;
	/* 水平居中 */
	margin: 0 auto;
}
```
![image](https://user-images.githubusercontent.com/13994442/99761418-0740a100-2b31-11eb-88d4-48c7fa7a009b.png)

###### 2.0 单个box的垂直居中
```css
.absolute-center {
	background-color: #909399;
	height: 100px;
	width: 200px;
	line-height: 100px;
	text-align: center;

	/* 垂直居中 */
	margin: auto;
	position: absolute;
	top: 0;
	left: 0;
	bottom: 0;
	right: 0;
}
```
![image](https://user-images.githubusercontent.com/13994442/99761435-13c4f980-2b31-11eb-9e68-a7b04068b1cd.png)

###### 2.1 容器container内的居中
```css
.absolute-center-1-p {
	height: 300px;
	position: relative;
	background-color: #1e5303;
}

.absolute-center-1 {
	background-color: #14a076;
	height: 50%;
	width: 50%;
	overflow: auto;
	margin: auto;
	position: absolute;
	top: 0;
	left: 0;
	bottom: 0;
	right: 0;
}
```
```html
<div class="absolute-center-1-p">
	<div class="absolute-center-1"> Hello World!</div>
</div>
```
![image](https://user-images.githubusercontent.com/13994442/99761447-1c1d3480-2b31-11eb-94ac-3abc6d59f5ff.png)

###### 2.2 容器container内的居中
```css
.is-transformed-parent {
	height: 300px;
	position: relative;
	background-color: #1e5303;
}

.is-transformed {
	background-color: #FFF;
	width: 50%;
	margin: auto;
	height: 50%;
	position: absolute;
	top: 50%;
	left: 50%;
	-webkit-transform: translate(-50%, -50%);
	-ms-transform: translate(-50%, -50%);
	transform: translate(-50%, -50%);
}
```
```html
<div class="is-transformed-parent">
	<div class="is-transformed"> Hello World!</div>
</div>
```
![image](https://user-images.githubusercontent.com/13994442/99761460-23444280-2b31-11eb-9309-97a95a3c09c1.png)

###### 2.3 容器container内的居中
```css
.display-container {
	background-color: #1e5303;
	display: flex;
	height: 150px;
	justify-content: center;
	align-items: center;
	color: #FFF;
}
```
```html
<div class="display-container">
	Hello World
</div>
```
![image](https://user-images.githubusercontent.com/13994442/99761469-29d2ba00-2b31-11eb-8483-543e2a032c6f.png)
